package EMS::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'DB::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:ems',
        user => 'ems',
        password => 'ems',
        AutoCommit => q{1},
    }
);

=head1 NAME

EMS::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<EMS>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<DB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
